// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:genlatte/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BaristaAdapter());
    registerAdapter(BaristaPersonaAdapter());
    registerAdapter(LatteAdapter());
    registerAdapter(LatteImageAdapter());
    registerAdapter(LatteImageBatchAdapter());
    registerAdapter(LatteOrderAdapter());
    registerAdapter(LatteOrderMetadataAdapter());
    registerAdapter(LatteOrderStatusAdapter());
    registerAdapter(MachineAdapter());
    registerAdapter(QuestionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BaristaAdapter());
    registerAdapter(BaristaPersonaAdapter());
    registerAdapter(LatteAdapter());
    registerAdapter(LatteImageAdapter());
    registerAdapter(LatteImageBatchAdapter());
    registerAdapter(LatteOrderAdapter());
    registerAdapter(LatteOrderMetadataAdapter());
    registerAdapter(LatteOrderStatusAdapter());
    registerAdapter(MachineAdapter());
    registerAdapter(QuestionAdapter());
  }
}
