// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/// @docImport 'package:genlatte_data/src/models/latte_order.dart';
library;

import 'package:data_layer/api.dart';
import 'package:data_layer/sources.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:genlatte_data/models.dart' show Question, QuestionConverter;

part 'latte_image.freezed.dart';
part 'latte_image.g.dart';

/// A set of 4 [LatteImage]s created for a [LatteOrder], to be viewed together.
@freezed
abstract class LatteImageBatch with _$LatteImageBatch {
  /// Instantiates a [LatteImageBatch].
  const factory LatteImageBatch({
    required String id,
    required String orderId,
    @LatteImageConverter() required LatteImage? image0,
    @LatteImageConverter() required LatteImage? image1,
    @LatteImageConverter() required LatteImage? image2,
    @LatteImageConverter() required LatteImage? image3,
    @LatteImageBatchParentConverter() LatteImageBatchParent? parent,
  }) = _LatteImageBatch;

  const LatteImageBatch._();

  /// Json deserializer for [LatteImageBatch].
  factory LatteImageBatch.fromJson(Map<String, Object?> json) =>
      _$LatteImageBatchFromJson(json);

  /// Iterates over all images.
  Iterable<LatteImage?> get images sync* {
    yield image0;
    yield image1;
    yield image2;
    yield image3;
  }

  /// Returns the image at the given index.
  LatteImage? operator [](int index) => switch (index) {
    0 => image0,
    1 => image1,
    2 => image2,
    3 => image3,
    _ => throw RangeError('Invalid image index: $index'),
  };

  /// Data Layer bindings for [LatteImageBatch].
  static Bindings<LatteImageBatch> bindings = Bindings<LatteImageBatch>(
    fromJson: LatteImageBatch.fromJson,
    toJson: (obj) => obj.toJson(),
    getId: (obj) => obj.id,
    getDetailUrl: (id) => ApiUrl(path: 'latteImageBatches/$id'),
    getListUrl: () => const ApiUrl(path: 'latteImageBatches'),
  );

  /// Returns a copy of the [LatteImageBatch] with the questions for the
  /// selected image updated.
  LatteImageBatch answerQuestion(
    int index,
    Question question,
    Object? answer,
  ) => switch (index) {
    0 => copyWith(image0: image0!.answerQuestion(question, answer)),
    1 => copyWith(image1: image1!.answerQuestion(question, answer)),
    2 => copyWith(image2: image2!.answerQuestion(question, answer)),
    3 => copyWith(image3: image3!.answerQuestion(question, answer)),
    _ => throw RangeError('Invalid image index: $index'),
  };
}

@freezed
/// Pointers toward the [LatteImageBatch] and specific image field that this
/// image batch forked from.
abstract class LatteImageBatchParent with _$LatteImageBatchParent {
  /// Instantiates a [LatteImageBatchParent].
  const factory LatteImageBatchParent({
    /// Firebase Id of the [LatteImageBatch] that this image batch forked from.
    required String id,

    /// "image0", "image1", "image2", or "image3". No other values are
    /// acceptable.
    required String imageIndex,
  }) = _LatteImageBatchParent;

  /// Json deserializer for [LatteImageBatchParent].
  factory LatteImageBatchParent.fromJson(Map<String, Object?> json) =>
      _$LatteImageBatchParentFromJson(json);
}

/// Candidate latte art generated by Nanobanana.
@freezed
abstract class LatteImage with _$LatteImage {
  /// Creates a new [LatteImage].
  const factory LatteImage({
    /// The URL of the generated image.
    required String imageUrl,

    /// The upgraded prompt sent to Gemini.
    required String prompt,

    @QuestionConverter() required List<Question>? questions,

    /// A description of the generated image.
    required String description,
  }) = _LatteImage;

  const LatteImage._();

  /// Json deserializer for [LatteImage].
  factory LatteImage.fromJson(Map<String, Object?> json) =>
      _$LatteImageFromJson(json);

  /// Returns a copy of the [LatteImage] with given question answered.
  LatteImage answerQuestion(Question question, Object? answer) {
    assert(
      questions != null && questions!.isNotEmpty,
      'Cannot answer questions on a LatteImage without any.',
    );
    final questionCopies = List<Question>.from(questions!);
    for (final (index, q) in questionCopies.indexed) {
      if (q.id == question.id) {
        questionCopies[index] = q.copyWithAnswer(answer);
        return copyWith(questions: questionCopies);
      }
    }
    throw Exception('Question ${question.id} not found in LatteImage.');
  }
}

/// Candidate latte art generated by Nanobanana.
@freezed
abstract class RecentLatteImage with _$RecentLatteImage {
  /// Creates a new [LatteImage].
  const factory RecentLatteImage({
    /// The URL of the generated image.
    required String imageUrl,

    /// The upgraded prompt sent to Gemini.
    required String prompt,

    /// The happy place that was used to generate the image.
    required String happyPlace,

    /// A description of the generated image.
    required String description,

    /// The name of the user who created this image.
    required String name,

    /// The time the originating [LatteOrder] was submitted and this document
    /// was created.
    required DateTime createdAt,

    /// The ID of the generated image.
    String? id,
  }) = _RecentLatteImage;

  const RecentLatteImage._();

  /// Json deserializer for [RecentLatteImage].
  factory RecentLatteImage.fromJson(Map<String, Object?> json) =>
      _$RecentLatteImageFromJson(json);

  /// Data Layer bindings for [RecentLatteImage] as recent images.
  static Bindings<RecentLatteImage> recentBindings = Bindings<RecentLatteImage>(
    fromJson: (data) {
      // When objects are brand new, they can briefly be emitted before the
      // server actually assigns a `createdAt` value. However, that missing
      // value will be very close to `now`, so that is a suitable fallback.
      final Object? createdAt = data['createdAt'];
      if (createdAt == null || (createdAt is String && createdAt.isEmpty)) {
        data['createdAt'] = DateTime.now().toUtc().toIso8601String();
      }
      return RecentLatteImage.fromJson(data);
    },
    toJson: (obj) => obj.toJson(),
    getId: (obj) => obj.id,
    getDetailUrl: (id) => ApiUrl(path: 'recentLatteImages/$id'),
    getListUrl: () => const ApiUrl(path: 'recentLatteImages'),
  );
}

/// {@template LatteImageConverter}
/// Json converter for [LatteImage].
/// {@endtemplate}
class LatteImageConverter
    extends JsonConverter<LatteImage, Map<String, Object?>> {
  /// {@macro LatteImageConverter}
  const LatteImageConverter();

  @override
  LatteImage fromJson(Map<String, Object?> json) => LatteImage.fromJson(json);

  @override
  Map<String, Object?> toJson(LatteImage object) => object.toJson();
}

/// {@template LatteImageBatchParentConverter}
/// Json converter for [LatteImageBatchParent].
/// {@endtemplate}
class LatteImageBatchParentConverter
    extends JsonConverter<LatteImageBatchParent, Map<String, Object?>> {
  /// {@macro LatteImageBatchParentConverter}
  const LatteImageBatchParentConverter();

  @override
  LatteImageBatchParent fromJson(Map<String, Object?> json) =>
      LatteImageBatchParent.fromJson(json);

  @override
  Map<String, Object?> toJson(LatteImageBatchParent object) => object.toJson();
}
