// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0mu0fBBQs2lNVCW861kkDTQSNcmBQjP4',
    appId: '1:177381243786:web:dea75ce782190ef7f6e673',
    messagingSenderId: '177381243786',
    projectId: 'gcdemos-26-int-dd-latteart',
    authDomain: 'gcdemos-26-int-dd-latteart.firebaseapp.com',
    databaseURL:
        'https://gcdemos-26-int-dd-latteart-default-rtdb.firebaseio.com',
    storageBucket: 'gcdemos-26-int-dd-latteart.firebasestorage.app',
    measurementId: "G-KHJ9QF44VC",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AlJnu87HVk3LtCtxBtk8hsyNJEJO_9I',
    appId: '1:177381243786:ios:b46a45bfd7ecca11f6e673',
    messagingSenderId: '177381243786',
    projectId: 'gcdemos-26-int-dd-latteart',
    authDomain: 'gcdemos-26-int-dd-latteart.firebaseapp.com',
    databaseURL:
        'https://gcdemos-26-int-dd-latteart-default-rtdb.firebaseio.com',
    storageBucket: 'gcdemos-26-int-dd-latteart.firebasestorage.app',
    measurementId: "G-KHJ9QF44VC",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqEHefNYgZ_GgKnnqhieD7O_qDvclbEI',
    appId: '1:177381243786:android:38afc480de87d7b2f6e673',
    messagingSenderId: '177381243786',
    projectId: 'gcdemos-26-int-dd-latteart',
    authDomain: 'gcdemos-26-int-dd-latteart.firebaseapp.com',
    databaseURL:
        'https://gcdemos-26-int-dd-latteart-default-rtdb.firebaseio.com',
    storageBucket: 'gcdemos-26-int-dd-latteart.firebasestorage.app',
    measurementId: "G-KHJ9QF44VC",
  );
}
