// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:genlatte/src/screens/app/app.dart';
import 'package:genlatte/src/widgets/widgets.dart';
import 'package:genlatte_data/models.dart';
import 'package:shadcn_flutter/shadcn_flutter.dart';

/// {@template BaristaPersonaCard}
/// A card for setting up a barista persona.
/// {@endtemplate}
class BaristaPersonaCard extends StatefulWidget {
  /// {@macro BaristaPersonaCard}
  const BaristaPersonaCard({
    required this.onSubmit,
    super.key,
  });

  /// Callback for when the user submits their persona.
  final void Function(String username, BaristaPersona persona) onSubmit;

  @override
  State<BaristaPersonaCard> createState() => _BaristaPersonaCardState();
}

class _BaristaPersonaCardState extends State<BaristaPersonaCard> {
  final TextEditingController _usernameController = TextEditingController();
  int? _selectedAvatarIndex;

  @override
  void initState() {
    super.initState();
    _usernameController.addListener(_onUsernameChanged);
  }

  void _onUsernameChanged() {
    setState(() {});
  }

  @override
  void dispose() {
    _usernameController.dispose();
    super.dispose();
  }

  // Generated by Gemini. Who knows.
  static const greyScaleMatrix = <double>[
    ...[0.2126, 0.7152, 0.0722, 0],
    ...[0, 0.2126, 0.7152, 0.0722],
    ...[0, 0, 0.2126, 0.7152],
    ...[0.0722, 0, 0, 0],
    ...[0, 0, 1, 0],
  ];

  static const _idealSize = Size(520, 520);

  @override
  Widget build(BuildContext context) {
    return ResponsiveSizedBox(
      aspectRatioClamp: (null, _idealSize.aspectRatio, null),
      child: LayoutProvider.builder(
        builder: (context, layoutInfo) {
          final scale = layoutInfo.constrainedScale(_idealSize);
          return Container(
            width: layoutInfo.width,
            padding: EdgeInsets.symmetric(
              horizontal: 24 * scale,
              vertical: 32 * scale,
            ),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(20 * scale),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.05),
                  blurRadius: 25 * scale,
                  offset: Offset(0, 10 * scale),
                ),
              ],
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Header
                Text(
                  'Set up your profile',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 24 * scale,
                    fontWeight: FontWeight.bold,
                    color: const Color(0xFF111827),
                  ),
                ),
                SizedBox(height: 8 * scale),
                Text(
                  'Choose a username and your avatar.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 14 * scale,
                    color: const Color(0xFF6B7280),
                  ),
                ),
                const SizedBox(height: 28),

                // Username Input
                Text(
                  'Username',
                  style: TextStyle(
                    fontSize: 13 * scale,
                    fontWeight: FontWeight.w600,
                    color: const Color(0xFF374151),
                  ),
                ),
                SizedBox(height: 8 * scale),
                TextField(
                  controller: _usernameController,
                  decoration: BoxDecoration(
                    border: Border.all(
                      color: AppColors.mutedGrey,
                    ), // defaults to BorderStyle.none
                    borderRadius: BorderRadius.all(
                      Radius.circular(8 * scale),
                    ),
                    color: Theme.of(context).colorScheme.input,
                  ),
                  // onChanged: widget.onSelected,
                  placeholder: Text(
                    'e.g. Your name',
                    style: TextStyle(fontSize: 16 * scale),
                  ),
                  padding: EdgeInsets.symmetric(
                    horizontal: 16 * scale,
                    vertical: 12 * scale,
                  ),
                  style: TextStyle(
                    fontSize: 16 * scale,
                  ),
                ),
                SizedBox(height: 24 * scale),

                // Avatar Grid
                Text(
                  'Select Avatar',
                  style: TextStyle(
                    fontSize: 13 * scale,
                    fontWeight: FontWeight.w600,
                    color: const Color(0xFF374151),
                  ),
                ),
                SizedBox(height: 8 * scale),
                GridView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 5,
                    crossAxisSpacing: 12,
                    mainAxisSpacing: 12,
                  ),
                  itemCount: BaristaPersona.values.length,
                  itemBuilder: (context, index) {
                    final isSelected = _selectedAvatarIndex == index;
                    return GestureDetector(
                      onTap: () {
                        setState(() {
                          _selectedAvatarIndex = index;
                        });
                      },
                      child: AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        curve: Curves.easeOut,
                        transform: isSelected
                            // ignore: deprecated_member_use
                            ? (Matrix4.identity()..scale(1.05))
                            : Matrix4.identity(),
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          border: Border.all(
                            color: isSelected
                                ? const Color(0xFF3B82F6)
                                : Colors.transparent,
                            width: 3 * scale,
                          ),
                          boxShadow: isSelected
                              ? [
                                  BoxShadow(
                                    color: const Color(
                                      0xFF3B82F6,
                                    ).withValues(alpha: 0.3),
                                    blurRadius: 10 * scale,
                                    offset: Offset(0, 4 * scale),
                                  ),
                                ]
                              : [],
                        ),
                        child: ClipOval(
                          child: ColorFiltered(
                            // Applies a grayscale effect to unselected avatars
                            colorFilter: isSelected
                                ? const ColorFilter.mode(
                                    Colors.transparent,
                                    BlendMode.multiply,
                                  )
                                : const ColorFilter.matrix(greyScaleMatrix),
                            child: Image.asset(
                              BaristaPersona.values[index].assetName,
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    );
                  },
                ),
                SizedBox(height: 32 * scale),

                // Submit Button
                PrimaryButton(
                  onPressed:
                      _usernameController.text.isNotEmpty &&
                          _selectedAvatarIndex != null
                      ? () {
                          widget.onSubmit(
                            _usernameController.text,
                            BaristaPersona.values[_selectedAvatarIndex!],
                          );
                        }
                      : null,
                  child: Center(
                    child: Padding(
                      padding: EdgeInsets.all(8 * scale),
                      child: Text(
                        'Get started',
                        style: TextStyle(
                          fontSize: 20 * scale,
                          color: AppColors.white,
                          fontWeight: FontWeight.w600,
                          letterSpacing: 0.7,
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
