import 'dart:math';

import 'package:genlatte/src/screens/app/app.dart' show AppColors;
import 'package:genlatte/src/screens/kiosk/widgets/loading_progress.dart';
import 'package:genlatte/src/screens/kiosk/widgets/widgets.dart';
import 'package:genlatte/src/screens/kiosk/widgets/zip_item.dart';
import 'package:genlatte/src/widgets/widgets.dart';
import 'package:genlatte_data/models.dart';
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:text_responsive/text_responsive.dart';

/// Header for the kiosk choose an image step.
class KioskChooseAnImageHeader extends StatelessWidget {
  /// Instantiates a [KioskChooseAnImageHeader].
  const KioskChooseAnImageHeader({super.key});

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.only(top: 8),
      child: ParagraphTextWidget(
        'Which one of these is closest\nto what you have in mind?',
        style: TextStyle(color: AppColors.white, fontSize: 20),
        textAlign: .center,
      ),
    );
  }
}

/// Revert button to sit above tweaked images.
class KioskChooseATweakedImageHeader extends StatelessWidget {
  /// Instantiates a [KioskChooseATweakedImageHeader].
  const KioskChooseATweakedImageHeader({
    required this.isReverting,
    required this.onRevert,
    super.key,
  });

  /// Whether the user is reverting to their original images.
  final bool isReverting;

  /// Callback to return a user to their original images.
  final VoidCallback? onRevert;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 8),
      child: Center(
        child: GenLatteOutlinedButton.light(
          onPressed: onRevert,
          label: !isReverting ? 'Revert to originals' : 'Reverting...',
        ),
      ),
    );
  }
}

const _emptyImages = <LatteImage?>[null, null, null, null];

/// The step in the kiosk wizard where the user chooses an image from the pool
/// of 4 generated by Nanobanana.
class KioskChooseAnImage extends StatelessWidget {
  /// Instantiates a [KioskChooseAnImage].
  const KioskChooseAnImage({
    required this.advanceToAcceptOrder,
    required this.advanceToTweakImage,
    required this.imagesBatch,
    required this.isSubmitting,
    required this.onSelectImage,
    required this.selectedIndex,
    required this.imageGenerationStartTime,
    super.key,
  });

  /// Callback to invoke when the user skips to the accept order step.
  final VoidCallback advanceToAcceptOrder;

  /// Callback to invoke when the user chooses an image.
  final VoidCallback? advanceToTweakImage;

  /// Callback to invoke when the user selects an image.
  final void Function(int) onSelectImage;

  /// Whether the user is submitting the order.
  final bool isSubmitting;

  /// User-selected latte art index.
  final int? selectedIndex;

  /// The images to display.
  final LatteImageBatch? imagesBatch;

  /// The time when image generation process started.
  ///
  /// A note on nullability: When choosing an image,
  /// the [imageGenerationStartTime] really shouldn't be null.
  /// But because of shenanigans around hot restart versus loading state
  /// from previous session, it's safer to assume nullable time
  /// and deal with it below in the widget tree.
  final DateTime? imageGenerationStartTime;

  @override
  Widget build(BuildContext context) {
    return LayoutProvider.builder(
      builder: (context, info) {
        return switch (info.aspectRatio) {
          < 1.6 => _LatteArtCarousel(
            advanceToTweakImage: advanceToTweakImage,
            advanceToAcceptOrder: advanceToAcceptOrder,
            imagesBatch: imagesBatch,
            layoutInfo: info,
            isSubmitting: isSubmitting,
            onSelectImage: onSelectImage,
            selectedIndex: selectedIndex,
            imageGenerationStartTime: imageGenerationStartTime,
          ),
          _ => _LatteArtField(
            advanceToAcceptOrder: advanceToAcceptOrder,
            advanceToTweakImage: advanceToTweakImage,
            imagesBatch: imagesBatch,
            layoutInfo: info,
            isSubmitting: isSubmitting,
            onSelectImage: onSelectImage,
            selectedIndex: selectedIndex,
            imageGenerationStartTime: imageGenerationStartTime,
          ),
        };
      },
    );
  }
}

class _LatteArtCarousel extends StatelessWidget {
  const _LatteArtCarousel({
    required this.advanceToAcceptOrder,
    required this.advanceToTweakImage,
    required this.imagesBatch,
    required this.isSubmitting,
    required this.layoutInfo,
    required this.onSelectImage,
    required this.selectedIndex,
    required this.imageGenerationStartTime,
  });

  final VoidCallback advanceToAcceptOrder;
  final VoidCallback? advanceToTweakImage;

  final LatteImageBatch? imagesBatch;
  final LayoutInformation layoutInfo;
  final bool isSubmitting;
  final void Function(int) onSelectImage;
  final int? selectedIndex;
  final DateTime? imageGenerationStartTime;

  @override
  Widget build(BuildContext context) {
    final images = imagesBatch?.images.toList() ?? _emptyImages;
    final realImagesCount = images.whereNotNull().length;

    final shouldShowButtons = realImagesCount > 0;

    return LayoutProvider.builder(
      builder: (context, info) {
        return Stack(
          clipBehavior: .none,
          fit: .expand,
          children: [
            Positioned(
              top: 0,
              left: 0,
              width: 0,
              height: 0,
              child: SizedBox.shrink(
                // This is here for ease of testing (while also preventing
                // a forced unmount of the whole widget tree).
                key: ValueKey('step-choose-image-${imagesBatch?.id ?? 'none'}'),
              ),
            ),
            Positioned.fill(
              child: Column(
                children: [
                  const Spacer(),
                  Expanded(
                    flex: 9,
                    child: Center(
                      child: SneakPeakCarousel(
                        children: <Widget>[
                          ...images.indexed.map<Widget>(
                            (imageAndIndex) {
                              if (images[imageAndIndex.$1] == null) {
                                return Padding(
                                  padding: info.aspectRatio > 1
                                      ? EdgeInsets.symmetric(
                                          vertical: info.height * 0.03,
                                        )
                                      : EdgeInsets.zero,
                                  child: EmptyLatteArt(
                                    key: ValueKey(imageAndIndex.$1.toString()),
                                  ),
                                );
                              }
                              return LayoutBuilder(
                                builder: (context, constraints) => ZipItem(
                                  index: 1,
                                  child: Column(
                                    mainAxisAlignment: .center,
                                    children: <Widget>[
                                      Center(
                                        child: SizedBox(
                                          width: min(
                                            constraints.maxWidth * 0.8,
                                            constraints.maxHeight * 0.8,
                                          ),
                                          child: Padding(
                                            padding: const EdgeInsets.all(4),
                                            child: _LatteArtImage(
                                              image: imageAndIndex.$2!,
                                              uiScale: 1,
                                              isSelected:
                                                  selectedIndex ==
                                                  imageAndIndex.$1,
                                              onTap: () {
                                                onSelectImage(imageAndIndex.$1);
                                              },
                                            ),
                                          ),
                                        ),
                                      ),
                                      const SizedBox(height: 12),
                                      ParagraphTextWidget(
                                        imageAndIndex.$2!.description,
                                        style: const TextStyle(
                                          color: AppColors.white,
                                          fontSize: 16,
                                        ),
                                        textAlign: .center,
                                        maxLines: 3,
                                      ),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                        ],
                      ),
                    ),
                  ),
                  Expanded(
                    flex: 3,
                    child: ZipItem(
                      index: 0,
                      child: Padding(
                        padding: const EdgeInsets.only(top: 16),
                        child: !shouldShowButtons
                            ? const SizedBox.shrink()
                            : Row(
                                mainAxisAlignment: .center,
                                children: <Widget>[
                                  const Spacer(),
                                  if (advanceToTweakImage != null) ...[
                                    Expanded(
                                      flex: 3,
                                      child: ResponsiveChevronButton(
                                        onPressed:
                                            (selectedIndex != null &&
                                                !isSubmitting)
                                            ? advanceToAcceptOrder
                                            : null,
                                        color: Colors.transparent,
                                        borderColor: AppColors.chevronYellow,
                                        textColor: AppColors.chevronYellow,
                                        style: .flat,
                                        text: 'Accept',
                                      ),
                                    ),
                                    Expanded(
                                      flex: 3,
                                      child: ResponsiveChevronButton(
                                        onPressed:
                                            (selectedIndex != null &&
                                                !isSubmitting)
                                            ? advanceToTweakImage
                                            : null,
                                        style: .flat,
                                        text: 'Tweak',
                                      ),
                                    ),
                                  ],

                                  if (advanceToTweakImage == null)
                                    Expanded(
                                      flex: 5,
                                      child: ResponsiveChevronButton(
                                        onPressed:
                                            (selectedIndex != null &&
                                                !isSubmitting)
                                            ? advanceToAcceptOrder
                                            : null,
                                        style: .flat,
                                        text: 'Accept',
                                      ),
                                    ),
                                  const Spacer(),
                                ],
                              ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            LoadingProgress(
              stillWaiting: realImagesCount == 0,
              progressStartTime: imageGenerationStartTime,
              padding: EdgeInsets.symmetric(
                horizontal: info.width * 0.05,
                vertical: info.height * 0.15,
              ),
            ),
          ],
        );
      },
    );
  }
}

class _LatteArtField extends StatelessWidget {
  const _LatteArtField({
    required this.advanceToAcceptOrder,
    required this.advanceToTweakImage,
    required this.imagesBatch,
    required this.isSubmitting,
    required this.layoutInfo,
    required this.onSelectImage,
    required this.selectedIndex,
    required this.imageGenerationStartTime,
  });

  /// Callback to invoke when the user skips to the accept order step.
  final VoidCallback? advanceToAcceptOrder;

  /// Callback to advance the wizard to the tweak image step.
  final VoidCallback? advanceToTweakImage;

  /// The images to display.
  final LatteImageBatch? imagesBatch;

  /// Whether the UI is submitting.
  final bool isSubmitting;

  /// The layout information for the current screen.
  final LayoutInformation layoutInfo;

  /// Callback for when the user selects a new image.
  final void Function(int) onSelectImage;

  /// Selected image.
  final int? selectedIndex;

  /// The time of start of image generation.
  final DateTime? imageGenerationStartTime;

  static const double _defaultWidth = 1024;
  static const double _defaultHeight = 768;

  @override
  Widget build(BuildContext context) {
    final images = imagesBatch?.images.toList() ?? _emptyImages;
    final realImagesCount = images.whereNotNull().length;
    final shouldShowButtons = realImagesCount > 0;
    return Row(
      children: <Widget>[
        const Spacer(),
        Expanded(
          flex: 9,
          child: LayoutProvider.builder(
            builder: (context, info) =>
                _buildLatteArtImages(context, info, images),
          ),
        ),
        Expanded(
          flex: 2,
          child: ZipItem(
            index: 0,
            child: !shouldShowButtons
                ? const SizedBox.shrink()
                : Column(
                    mainAxisAlignment: .center,
                    children: <Widget>[
                      if (advanceToTweakImage != null) ...[
                        ResponsiveChevronButton(
                          onPressed: (selectedIndex != null && !isSubmitting)
                              ? advanceToTweakImage
                              : null,
                          style: .flat,
                          text: 'Tweak',
                        ),
                        const SizedBox(height: 16),
                        ResponsiveChevronButton(
                          onPressed: (selectedIndex != null && !isSubmitting)
                              ? advanceToAcceptOrder
                              : null,
                          color: Colors.transparent,
                          borderColor: AppColors.chevronYellow,
                          textColor: AppColors.chevronYellow,
                          style: .flat,
                          text: 'Accept',
                        ),
                      ],
                      if (advanceToTweakImage == null)
                        ResponsiveChevronButton(
                          onPressed: (selectedIndex != null && !isSubmitting)
                              ? advanceToAcceptOrder
                              : null,
                          style: .vertical,
                          scale: 0.6,
                          text: 'Accept',
                        ),
                    ],
                  ),
          ),
        ),
      ],
    );
  }

  Widget _buildLatteArtImages(
    BuildContext context,
    LayoutInformation info,
    List<LatteImage?> images,
  ) {
    final realImagesCount = images.whereNotNull().length;

    final scale = info.unconstrainedScale(
      const Size(_defaultWidth, _defaultHeight),
    );

    // Get the default latte art image positions
    final latteArtPositions = _latteArtRowPositions(info, scale);

    // Now shift things around to accentuate the selected image
    if (selectedIndex != null) {
      _accentuateActiveImageInRow(latteArtPositions, scale);
    }

    return Stack(
      clipBehavior: .none,
      fit: .expand,
      children: [
        Positioned(
          top: 0,
          left: 0,
          width: 0,
          height: 0,
          child: SizedBox.shrink(
            // This is here for ease of testing (while also preventing
            // a forced unmount of the whole widget tree).
            key: ValueKey('step-choose-image-${imagesBatch?.id ?? 'none'}'),
          ),
        ),
        ...latteArtPositions.indexed.map<Widget>(
          (positionAndIndex) {
            final image = images[positionAndIndex.$1];
            final child = image == null
                ? const EmptyLatteArt()
                : ZipItem(
                    index: latteArtPositions.length - positionAndIndex.$1,
                    child: _LatteArtImage(
                      image: image,
                      uiScale: scale,
                      onTap: () {
                        onSelectImage(positionAndIndex.$1);
                      },
                      isSelected: selectedIndex == positionAndIndex.$1,
                    ),
                  );
            return AnimatedPositioned(
              duration: const Duration(seconds: 2),
              curve: Curves.elasticOut,
              top: positionAndIndex.$2.center.dy - positionAndIndex.$2.size / 2,
              left:
                  positionAndIndex.$2.center.dx - positionAndIndex.$2.size / 2,
              width: positionAndIndex.$2.size,
              height: positionAndIndex.$2.size,
              key: image != null
                  ? ValueKey(images[positionAndIndex.$1]!.imageUrl)
                  : null,
              child: child,
            );
          },
        ),
        ...latteArtPositions.indexed.map<Widget?>(
          (positionAndIndex) {
            if (images[positionAndIndex.$1] == null) {
              return null;
            }
            return Positioned(
              top:
                  positionAndIndex.$2.center.dy +
                  positionAndIndex.$2.size / 2 + // bottom of the image
                  12, // vertical margin
              left: max(
                positionAndIndex.$2.center.dx - positionAndIndex.$2.size / 2,
                0,
              ),
              width: positionAndIndex.$2.size,
              height: 100 * scale,
              key: ValueKey(
                '${images[positionAndIndex.$1]}--'
                '${images[positionAndIndex.$1]!.description}',
              ),
              child: ZipItem(
                index: latteArtPositions.length - positionAndIndex.$1,
                child: ParagraphTextWidget(
                  images[positionAndIndex.$1]!.description,
                  style: TextStyle(
                    color: AppColors.white,
                    fontSize: 28 * scale,
                  ),
                  textAlign: .center,
                  maxLines: positionAndIndex.$1 == selectedIndex ? 3 : 4,
                ),
              ),
            );
          },
        ).whereNotNull(),
        LoadingProgress(
          stillWaiting: realImagesCount == 0,
          progressStartTime: imageGenerationStartTime,
          padding: EdgeInsets.symmetric(
            horizontal: info.width * 0.05,
            vertical: info.height * 0.05,
          ),
        ),
      ],
    );
  }

  List<_LatteArtPosition> _latteArtRowPositions(
    LayoutInformation info,
    double scale,
  ) {
    return [
      _LatteArtPosition(
        center: Offset(
          info.constraints.maxWidth * 0.12,
          info.constraints.maxHeight * 0.35,
        ),
        size: 150 * scale,
      ),
      _LatteArtPosition(
        center: Offset(
          info.constraints.maxWidth * 0.35,
          info.constraints.maxHeight * 0.5,
        ),
        size: 150 * scale,
      ),
      _LatteArtPosition(
        center: Offset(
          info.constraints.maxWidth * 0.58,
          info.constraints.maxHeight * 0.4,
        ),
        size: 150 * scale,
      ),
      _LatteArtPosition(
        center: Offset(
          info.constraints.maxWidth * 0.81,
          info.constraints.maxHeight * 0.45,
        ),
        size: 150 * scale,
      ),
    ];
  }

  /// Performs in-place modifications to [latteArtPositions] to make the
  /// selected image larger and the other images shift away from the selected
  /// image, all assuming the row layout.
  void _accentuateActiveImageInRow(
    List<_LatteArtPosition> latteArtPositions,
    double scale,
  ) {
    latteArtPositions[selectedIndex!] = latteArtPositions[selectedIndex!].scale(
      1.5,
    );

    int delta = 1;
    while (delta < latteArtPositions.length) {
      final lowerIndexToModify = selectedIndex! - delta;
      if (lowerIndexToModify >= 0) {
        latteArtPositions[lowerIndexToModify] =
            latteArtPositions[lowerIndexToModify].shiftAwayFrom(
              latteArtPositions[selectedIndex!].center,
              scale,
            );
      }

      final upperIndexToModify = selectedIndex! + delta;
      if (upperIndexToModify < latteArtPositions.length) {
        latteArtPositions[upperIndexToModify] =
            latteArtPositions[upperIndexToModify].shiftAwayFrom(
              latteArtPositions[selectedIndex!].center,
              scale,
            );
      }
      delta++;
    }
  }
}

class _LatteArtImage extends StatelessWidget {
  const _LatteArtImage({
    required this.image,
    required this.isSelected,
    required this.onTap,
    required this.uiScale,
  });

  /// The image to display.
  final LatteImage image;

  /// Whether the image is selected.
  final bool isSelected;

  /// Callback to invoke when the user taps the image.
  final VoidCallback onTap;

  /// The color of the halo.
  static const Color haloColor = AppColors.googleBlue;

  /// The scale of the UI.
  final double uiScale;

  @override
  Widget build(BuildContext context) {
    Widget child = LatteImageWidget(imageUrl: image.imageUrl);

    if (isSelected) {
      child = Container(
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          boxShadow: [
            BoxShadow(
              color: haloColor.withValues(
                alpha: 0.8,
              ), // Adjust opacity for desired intensity
              blurRadius: 8 * uiScale, // How soft the edge of the glow is
              spreadRadius: 8 * uiScale, // How much the glow expands outwards
              // Default offset of Offset.zero centers the glow around the image
            ),
          ],
        ),
        child: child,
      );
    } else {
      child = GestureDetector(onTap: onTap, child: child);
    }

    return child;
  }
}

class _LatteArtPosition {
  const _LatteArtPosition({
    required this.center,
    required this.size,
  });

  final Offset center;
  final double size;

  _LatteArtPosition scale(double scale) {
    return _LatteArtPosition(
      center: center,
      size: size * scale,
    );
  }

  _LatteArtPosition shiftAwayFrom(Offset otherCenter, double uiScale) {
    return _LatteArtPosition(
      center: Offset(
        center.dx + (center.dx - otherCenter.dx) * 0.05 * uiScale,
        center.dy + (center.dy - otherCenter.dy) * 0.05 * uiScale,
      ),
      size: size,
    );
  }
}

extension _FilterableList<T> on Iterable<T?> {
  Iterable<T> whereNotNull() {
    return where((T? element) => element != null).cast<T>();
  }
}
