export 'kiosk_choose_an_image.dart';
export 'kiosk_confirmation.dart';
export 'kiosk_drink_milk_sweetener.dart';
export 'kiosk_drink_order_name.dart';
export 'kiosk_happy_place.dart';
export 'kiosk_intro.dart';
export 'kiosk_step.dart';
export 'kiosk_submit_order.dart';
export 'kiosk_tweak_image.dart';
