import 'dart:io';

import 'package:ffigen/ffigen.dart' as fg;
import 'package:logging/logging.dart';
import 'package:pub_semver/pub_semver.dart';
import 'package:swift2objc/swift2objc.dart' as swift2objc;
import 'package:swiftgen/swiftgen.dart';

Future<void> main() async {
  final logger = Logger('swiftgen');
  logger.onRecord.listen((record) {
    stderr.writeln('${record.level.name}: ${record.message}');
  });

  await SwiftGenerator(
    target: Target(
      triple: 'x86_64-apple-macosx14.0',
      sdk: Uri.directory(
        '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk',
      ),
    ),
    inputs: const [SwiftModuleInput(module: 'EventKit')],
    include: (swift2objc.Declaration d) {
      if (d.name == 'birthdayPersonUniqueID') return false;
      // Also exclude anything deprecated we might run into
      return d.name == 'EKEventStore' ||
          d.name == 'EKEvent' ||
          d.name == 'EKCalendar';
    },
    output: Output(
      swiftWrapperFile: SwiftWrapperFile(
        path: Uri.file('ios/Runner/eventkit_wrapper.swift'),
      ),
      module: 'EventKitWrapper',
      dartFile: Uri.file('lib/eventkit_bindings.dart'),
      objectiveCFile: Uri.file('ios/Runner/eventkit_wrapper.m'),
      preamble: '''
// Copyright (c) 2025, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Auto-generated by swiftgen
// coverage:ignore-file
''',
    ),
    ffigen: FfiGeneratorOptions(
      objectiveC: fg.ObjectiveC(
        externalVersions: fg.ExternalVersions(
          ios: fg.Versions(min: Version(14, 0, 0)),
        ),
        interfaces: fg.Interfaces(
          include: (decl) =>
              decl.originalName == 'EKEventStoreWrapper' ||
              decl.originalName == 'EKEventWrapper' ||
              decl.originalName == 'EKCalendarWrapper',
        ),
      ),
    ),
  ).generate(logger: logger, tempDirectory: Uri.directory('temp'));

  print(
    'Code generation complete. Stripping unavailable iOS properties from Swift wrapper...',
  );

  final swiftFile = File('ios/Runner/eventkit_wrapper.swift');
  if (swiftFile.existsSync()) {
    var content = swiftFile.readAsStringSync();

    // Remove birthdayPersonUniqueID
    content = content.replaceAll(
      RegExp(
        r'\s*@objc public var birthdayPersonUniqueID: String\? \{[\s\S]*?\}\s*\}',
      ),
      '',
    );

    swiftFile.writeAsStringSync(content);
    print('Stripped birthdayPersonUniqueID successfully.');
  }

  print('Done.');
}
