import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  print('Generating EventKit bindings directly from Objective-C headers...');
  final generator = FfiGenerator(
    headers: Headers(
      entryPoints: [
        Uri.file(
          '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/EventKit.framework/Headers/EventKit.h',
        ),
      ],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'EKEventStore',
        'EKEvent',
        'EKCalendar',
        'EKCalendarItem',
        'EKObject',
      }),
    ),
    enums: Enums.includeSet({'EKEntityType'}),
    output: Output(
      dartFile: Uri.file('lib/eventkit_bindings.dart'),
      preamble: '''
// Copyright (c) 2025, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Auto-generated by swiftgen
// coverage:ignore-file
''',
    ),
  );

  generator.generate();

  // Clean up old swiftgen wrapper files since they are no longer needed
  final swiftFile = File('ios/Runner/eventkit_wrapper.swift');
  if (swiftFile.existsSync()) swiftFile.deleteSync();

  final objcFileOld = File('ios/Runner/eventkit_wrapper.m');
  if (objcFileOld.existsSync()) objcFileOld.deleteSync();

  print('Done.');
}
